//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod7
{
    using System;
    using System.Collections.Generic;
    
    public partial class PutniNalog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PutniNalog()
        {
            this.Ruta = new HashSet<Ruta>();
        }
    
        public int IDPutniNalog { get; set; }
        public string Naredbodavac { get; set; }
        public int BrojNaloga { get; set; }
        public int VozacID { get; set; }
        public int VoziloID { get; set; }
        public string Polaziste { get; set; }
        public string Odrediste { get; set; }
        public int BrojDana { get; set; }
        public System.DateTime DatumOtvaranja { get; set; }
        public Nullable<System.DateTime> DatumZatvaranja { get; set; }
    
        public virtual Vozac Vozac { get; set; }
        public virtual Vozilo Vozilo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ruta> Ruta { get; set; }
    }
}
