//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ruta
    {
        public int IDRuta { get; set; }
        public int Sati { get; set; }
        public double KoordinataA { get; set; }
        public double KoordinataB { get; set; }
        public int PutniNalogID { get; set; }
        public int PrijedeniKilometri { get; set; }
        public int ProsjecnaBrzina { get; set; }
        public double PotrosenoGorivo { get; set; }
    
        public virtual PutniNalog PutniNalog { get; set; }
    }
}
