//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servis
    {
        public int IDServis { get; set; }
        public string Opis { get; set; }
        public System.DateTime Datum { get; set; }
        public Nullable<int> VoziloID { get; set; }
    
        public virtual Vozilo Vozilo { get; set; }

        public override string ToString()
        {
            return Opis;
        }
    }
}
