//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ishod7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vozilo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vozilo()
        {
            this.PutniNalog = new HashSet<PutniNalog>();
            this.Servis = new HashSet<Servis>();
        }
    
        public int IDVozilo { get; set; }
        public string Tip { get; set; }
        public string Marka { get; set; }
        public int GodinaProizvodnje { get; set; }
        public int PrijedeniKilometri { get; set; }
        public bool JeSlobodno { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PutniNalog> PutniNalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Servis> Servis { get; set; }

        public override string ToString()
        {
            return Tip + " - " + Marka; 
        }
    }
}
